server.port: 8081

spring:
  # DB
  datasource:
    url: jdbc:mariadb://localhost:3307/license_service_db?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true
    defer-datasource-initialization: true

# JWT
jwt:
  secret: dGVhbWRldi1hdXRoLWp3dC1teS1zZWNyZXQta2V5LXRlYW1kZXYtYXV0aC1qd3QtbXktc2VjcmV0LWtleS10ZWFtZGV2LWF1dGgtand0LW15LXNlY3JldC1rZXktdGVhbWRldi1hdXRoLWp3dC1teS1zZWNyZXQta2V5Cg==
  token-validity-in-seconds: 86400